### ISSUE TITLE
Turn USE_BTREE into crate feature

### ISSUE THREAD

**Issue by imp** [ideasman42/rangetree-rs#4]
Instead of source code make USE_BTREE a crate feature. The choice will eliminate any possible run-time overhead of that decision (to use BTree or not)

**Comment by ideasman42** [comment]
Firstly, there won't be any runtime overhead, I double checked that this gets optimized out (its a local boolean constant).

Further not sure it makes sense to for `USE_BTREE` to be a crate feature.

The only reason to use this is when debugging the crate it's self, so the chances anyone else would want to look into this is near zero.

OTOH `#[cfg(feature = "foo")]` could read a little more logically in the code.

Not sure on this one, is it common to add features to an entire crate just for debugging a single file?

**Comment by imp** [comment]
Well this is a compile time option, right ? Spells `feature` in my book 😄 
It is easy to make it opt-out or opt-in by either listing it in `features.default` list or not.

**Comment by ideasman42** [comment]
Right, the point is its only a compile time option the developer of the library would be interested in. Not something a user of the crate should ever see.

**Comment by ideasman42** [comment]
Updated, asked [File or module level 'feature' possible?](http://stackoverflow.com/questions/42406538) - the answer shows this can be done using a build-script.

It seems over-kill to add a build script just to toggle a feature which works reasonably well with a constant.

@imp are you interested to look into this?

**Comment by imp** [comment]
Well, I've looked into this. Didn't like what I saw.

First, I agree with you on build.rs - total overkill for intended result.
Second, tried to do it with opt-out feature and arrived at enabling some unstable features
(`#![feature(stmt_expr_attributes)]` and friends). Losing stable support definitely too high price to pay.

So I am pulling it back and closing this issue.
